name: Main

on:
  push:
    branches:
      - main

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        cd frontend
        npm install

    - name: Run Jest Tests
      run: npm run test --prefix frontend
  
  frontend-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  backend-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        cd backend
        npm install

    - name: Run Jest Tests
      run: npm run test --prefix backend

  backend-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  frontend-build:
    runs-on: ubuntu-latest
    needs: [frontend-unit-tests, frontend-integration-tests]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install
      working-directory: frontend

    - name: Build
      run: npm run build
      working-directory: frontend

  backend-build:
    runs-on: ubuntu-latest
    needs: [backend-unit-tests, backend-integration-tests]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install
      working-directory: backend

    - name: Build
      run: npm run build
      working-directory: backend

  deployment:
    runs-on: ubuntu-latest
    # needs: [backend-build, frontend-build]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Create S3 Bucket
      run: |
        aws s3api create-bucket --bucket 023450234-frontend-bucket-${{ github.ref_slug }} --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1

    - name: Deploy to S3
      run: |
        aws s3 sync ./frontend s3://023450234-frontend-bucket-${{ github.ref_slug }} --delete